apiVersion: v1
kind: Service
metadata:
  name: helloworldkubewebmvcservice
spec:
  selector:
    app: helloworldkubewebmvc
    tier: web
  type: NodePort
  ports:
  - port: 80   
    nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldkubewebmvcdeployment
spec:
  selector:
    matchLabels:
      app: helloworldkubewebmvc
      tier: web
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworldkubewebmvc
        tier: web
        track: stable
    spec:
      containers:
      - name: helloworldkubewebmvc
        image: "shyamslab/helloworldkubewebmvc:20181228.1"
        env:
        - name: HelloWorldApiUrl
          value: "http://helloworldkubeapiservice:30080"
        ports:
          - name: http
            containerPort: 80
