apiVersion: v1
kind: Service
metadata:
  name: helloworldkubeapiservice
spec:
  selector:
    app: helloworldkubeapi
    tier: api
  type: LoadBalancer
  ports:
  - port: 80   
    nodePort: 30080
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldkubeapideployment
spec:
  selector:
    matchLabels:
      app: helloworldkubeapi
      tier: api
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworldkubeapi
        tier: api
        track: stable
    spec:
      containers:
      - name: helloworldkubeapi
        image: "shyamslab/helloworldkubeapi:20181228.6"
        ports:
          - name: http
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworldkubewebmvcservice
spec:
  selector:
    app: helloworldkubewebmvc
    tier: web
  type: LoadBalancer
  ports:
  - port: 80   
    nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldkubewebmvcdeployment
spec:
  selector:
    matchLabels:
      app: helloworldkubewebmvc
      tier: web
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworldkubewebmvc
        tier: web
        track: stable
    spec:
      containers:
      - name: helloworldkubewebmvc
        image: "shyamslab/helloworldkubewebmvc:20181228.1"
        env:
        - name: HelloWorldApiUrl
          value: "http://helloworldkubeapiservice"
        ports:
          - name: http
            containerPort: 80
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: helloworldkube-mssql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
        tier: apistorage
        track: stable
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: dbik8registry.azurecr.io/dbi_linux_sql2017:CU4
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
