apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldkubeapi
spec:
  selector:
    matchLabels:
      app: helloworldkubeapi
      tier: api
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworldkubeapi
        tier: api
        track: stable
    spec:
      containers:
        - name: helloworldkubeapi
          image: "shyamslab/helloworldkubeapi:20181228.6"
          ports:
            - name: http
              containerPort: 80       
        - name: helloworldkubewebmvc
          image: "image=shyamslab/helloworldkubewebmvc:20181228.1"
          ports:
            - name: http
              containerPort: 80
